require "config.plugins.catppuccin"
require "config.plugins.lualine"
require "config.plugins.treesitter"
require "config.plugins.bufferline"
require "config.plugins.nvim-notify"
require "config.plugins.which-key"
require "config.plugins.nvim-tree"
